---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name:  cloudsql-credentials
data:
  credentials.json: |-
    < your base64 encoded key >
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsql-proxy
  template:
    metadata:
      labels:
        app: cloudsql-proxy
    spec:
      securityContext:
        runAsUser: 2
        allowPrivilegeEscalation: false
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.12
          command: [
            "/cloud_sql_proxy",
            "-instances=my-project:my-region:my-instance=tcp:3306",
            "-credential_file=/secrets/cloudsql/credentials.json"
          ]
          volumeMounts:
            - name: cloudsql-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          resources:
            requests:
              cpu: 5m
              memory: 16M
            limits:
              cpu: 500m
              memory: 64M
      volumes:
        - name: cloudsql-credentials
          secret:
            secretName: cloudsql-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: cloudsql-proxy
spec:
  type: ClusterIP
  selector:
    app: cloudsql-proxy
  ports:
    - port: 3306
      targetPort: 3306            